.DEFAULT_GOAL := help

STACK ?= woodglass_affine_dev

AFFINE_SERVER_PORT ?= 3910
WEB_PORT ?= 3900

DB_PORT ?= 55432
REDIS_PORT ?= 56379
MAILHOG_SMTP_PORT ?= 51025
MAILHOG_WEB_PORT ?= 58025
MANTICORE_PORT ?= 59308

DB_USERNAME ?= affine
DB_PASSWORD ?= affine
DB_DATABASE_NAME ?= affine

COMPOSE_FILE := ./.docker/dev/compose.yml
COMPOSE_ENV_FILE := ./.docker/dev/.env
BACKUP_DIR := ./.docker/dev/backups

.PHONY: help
help:
	@echo "Dev workflow (STACK=$(STACK))"
	@echo ""
	@echo "  make dev-services-init        Create .docker/dev/.env + compose.yml (if missing)"
	@echo "  make dev-services-up          Start postgres/redis/mailhog/manticore"
	@echo "  make dev-services-down        Stop services (keeps volumes)"
	@echo "  make dev-services-ps          Show services"
	@echo "  make dev-services-logs        Tail services logs"
	@echo ""
	@echo "  make dev-server-env           Create packages/backend/server/.env (if missing)"
	@echo "  make dev-server-init          Run migrations/init"
	@echo "  make dev-server               Start @affine/server (AFFINE_SERVER_PORT=$(AFFINE_SERVER_PORT))"
	@echo ""
	@echo "  make dev-web                  Start @affine/web (WEB_PORT=$(WEB_PORT))"
	@echo ""
	@echo "  make db-dump                  Dump postgres to $(BACKUP_DIR)/<stack>-<ts>.sql"
	@echo "  make db-restore BACKUP=...    Restore postgres from sql file"
	@echo ""
	@echo "Override ports by env vars, e.g.:"
	@echo "  STACK=wg2 DB_PORT=55433 REDIS_PORT=56380 WEB_PORT=3901 AFFINE_SERVER_PORT=3911 make dev-services-up"

.PHONY: dev-services-init
dev-services-init:
	@test -f "$(COMPOSE_ENV_FILE)" || cp ./.docker/dev/.env.example "$(COMPOSE_ENV_FILE)"
	@test -f "$(COMPOSE_FILE)" || cp ./.docker/dev/compose.yml.example "$(COMPOSE_FILE)"
	@mkdir -p "$(BACKUP_DIR)"
	@echo "Initialized $(COMPOSE_ENV_FILE) and $(COMPOSE_FILE)"
	@echo "Edit $(COMPOSE_ENV_FILE) if you want to change ports or credentials."

.PHONY: dev-services-up
dev-services-up: dev-services-init
	docker compose --env-file "$(COMPOSE_ENV_FILE)" -f "$(COMPOSE_FILE)" -p "$(STACK)" up -d

.PHONY: dev-services-down
dev-services-down:
	docker compose --env-file "$(COMPOSE_ENV_FILE)" -f "$(COMPOSE_FILE)" -p "$(STACK)" down

.PHONY: dev-services-ps
dev-services-ps:
	docker compose --env-file "$(COMPOSE_ENV_FILE)" -f "$(COMPOSE_FILE)" -p "$(STACK)" ps

.PHONY: dev-services-logs
dev-services-logs:
	docker compose --env-file "$(COMPOSE_ENV_FILE)" -f "$(COMPOSE_FILE)" -p "$(STACK)" logs -f --tail=200

.PHONY: dev-server-env
dev-server-env:
	@test -f packages/backend/server/.env || ( \
		echo "# Generated by Makefile (STACK=$(STACK))" > packages/backend/server/.env && \
		echo "DATABASE_URL=postgres://$(DB_USERNAME):$(DB_PASSWORD)@localhost:$(DB_PORT)/$(DB_DATABASE_NAME)" >> packages/backend/server/.env && \
		echo "REDIS_SERVER_HOST=localhost" >> packages/backend/server/.env && \
		echo "REDIS_SERVER_PORT=$(REDIS_PORT)" >> packages/backend/server/.env && \
		echo "MAILER_HOST=127.0.0.1" >> packages/backend/server/.env && \
		echo "MAILER_PORT=$(MAILHOG_SMTP_PORT)" >> packages/backend/server/.env && \
		echo "AFFINE_SERVER_HOST=localhost" >> packages/backend/server/.env && \
		echo "AFFINE_SERVER_PORT=$(AFFINE_SERVER_PORT)" >> packages/backend/server/.env && \
		echo "AFFINE_SERVER_HTTPS=false" >> packages/backend/server/.env && \
		echo "Created packages/backend/server/.env"; \
	)

.PHONY: dev-server-init
dev-server-init: dev-services-up dev-server-env
	yarn affine server init

.PHONY: dev-server
dev-server: dev-services-up dev-server-env
	AFFINE_SERVER_PORT="$(AFFINE_SERVER_PORT)" yarn affine server dev

.PHONY: dev-web
dev-web:
	PORT="$(WEB_PORT)" yarn affine dev -p @affine/web

.PHONY: db-dump
db-dump: dev-services-up
	@mkdir -p "$(BACKUP_DIR)"
	@ts="$$(date +%Y%m%d-%H%M%S)"; \
	out="$(BACKUP_DIR)/$(STACK)-$$ts.sql"; \
	echo "Dumping to $$out"; \
	docker compose --env-file "$(COMPOSE_ENV_FILE)" -f "$(COMPOSE_FILE)" -p "$(STACK)" exec -T \
		-e PGPASSWORD="$(DB_PASSWORD)" postgres \
		pg_dump -U "$(DB_USERNAME)" --clean --if-exists --no-owner --no-privileges "$(DB_DATABASE_NAME)" > "$$out"

.PHONY: db-restore
db-restore: dev-services-up
	@test -n "$(BACKUP)" || (echo "Usage: make db-restore BACKUP=./.docker/dev/backups/<file>.sql" && exit 1)
	@test -f "$(BACKUP)" || (echo "Backup file not found: $(BACKUP)" && exit 1)
	@echo "Restoring from $(BACKUP)"
	cat "$(BACKUP)" | docker compose --env-file "$(COMPOSE_ENV_FILE)" -f "$(COMPOSE_FILE)" -p "$(STACK)" exec -T \
		-e PGPASSWORD="$(DB_PASSWORD)" postgres \
		psql -U "$(DB_USERNAME)" -d "$(DB_DATABASE_NAME)"
